version: "3.8"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=
      - GITEA__database__HOST=
      - GITEA__database__NAME=
      - GITEA__database__USER=
      - GITEA__database__PASSWD=
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-dev:/data
      - gitea-tz:/etc/timezone:ro
      - gitea-lz:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    networks:
      - gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  gitea-dev:
  gitea-tz:
  gitea-lz:
