version: '3.8'
services:
  web:
    image: odoo:17
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - web:/var/lib/odoo
      - config:/etc/odoo
      - addons:/mnt/extra-addons
    environment:
      - HOST=POSTGRES_HOST
      - PORT=POSTGRES_PORT
      - USER=POSTGRES_USER
      - PASSWORD=POSTGRES_PASSWORD
      - DB=POSTGRES_DBNAME

volumes:
  web:
  config:
  addons:
