version: '3.8'
services:
  database:
    restart: always
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data/pgdata

volumes:
  data:
