# Setup composer
- name: Setup Composer
  hosts: localhost
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes
      become_user: "{{ ansible_user_id }}"

    - name: Upgrade cache
      apt:
        upgrade: 'yes'
      become_user: "{{ ansible_user_id }}"

    - name: Install MySQL Ansible
      ansible.builtin.shell: ansible-galaxy role install geerlingguy.mysql

    - name: Install PostgreSQL Ansible
      ansible.builtin.shell: ansible-galaxy role install geerlingguy.postgresql

    - name: Install PHP-CLI and Unzip
      apt:
        name:
          - php-cli
          - unzip
        state: present
      become_user: "{{ ansible_user_id }}"

    - name: Download Composer File
      ansible.builtin.shell: |
        cd ~ &&
        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

    - name: Check Composer Hash
      ansible.builtin.shell: |
        HASH=`curl -sS https://composer.github.io/installer.sig` &&
        echo $HASH

    - name: Install Composer
      ansible.builtin.shell: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

    - name: Install Composer globally
      ansible.builtin.shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      become_user: "{{ ansible_user_id }}"