# Setup Nginx server
- name: Setup Web Server
  hosts: localhost
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes
      become_user: "{{ ansible_user_id }}"

    - name: Upgrade cache
      apt:
        upgrade: 'yes'
      become_user: "{{ ansible_user_id }}"

    - name: Install PHP Version 8.1
      apt:
        name:
          - php8.1
          - php8.1-cli
          - php8.1-common
          - php8.1-mysql
          - php8.1-zip
          - php8.1-gd
          - php8.1-mbstring
          - php8.1-curl
          - php8.1-xml
          - php8.1-bcmath
          - php8.1-fpm
        install_recommends: no
        state: present
      become_user: "{{ ansible_user_id }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become_user: "{{ ansible_user_id }}"

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become_user: "{{ ansible_user_id }}"

    - name: Start PHP FPM Sock Service
      service:
        name: php8.1-fpm
        state: started
      become_user: "{{ ansible_user_id }}"

    - name: Install Laravel Project Dependencies
      ansible.builtin.shell: |
        cd ~ &&
        cd devops-practice/stackingsandbox &&
        composer install &&
        cp .env.example .env &&
        php artisan key:generate &&

    - name: Move Laravel Project to Web Server and Change Permissions
      ansible.builtin.shell: |
        cd ~ &&
        mv devops-practice/stackingsandbox /var/www/ &&
        cd /var/www/stackingsandbox/ &&
        chown -R $USER:www-data . &&
        find . -type f -exec chmod 644 {} \; &&
        find . -type d -exec chmod 775 {} \; &&
        chgrp -R www-data storage bootstrap/cache &&
        chmod -R ug+rwx storage bootstrap/cache
      become_user: "{{ ansible_user_id }}"

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become_user: "{{ ansible_user_id }}"

  vars: