# Setup Nginx server
- name: Setup Web Server
  hosts: localhost

  tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade cache
      become: yes
      apt:
        upgrade: 'yes'

    - name: Install PHP Version 8.1
      become: yes
      apt:
        name:
          - php8.1
          - php8.1-cli
          - php8.1-common
          - php8.1-mysql
          - php8.1-zip
          - php8.1-gd
          - php8.1-mbstring
          - php8.1-curl
          - php8.1-xml
          - php8.1-bcmath
        install_recommends: no
        state: present

    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      become: yes
      service:
        name: nginx
        state: started

    - name: Install Laravel Project Dependencies
      ansible.builtin.shell: |
        cd ~ &&
        cd devops-practice/stackingsandbox &&
        composer install &&
        cp .env.example .env &&
        php artisan key:generate

    - name: Move Laravel Project to Web Server
      ansible.builtin.shell: |
        cd ~ &&
        sudo mv devops-practice/stackingsandbox /var/www/html/

  handlers:
    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted

  vars: