# Setup Nginx server
- name: Setup Web Server
  hosts: localhost
  become: yes

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgrade cache
      apt:
        upgrade: 'yes'

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  vars: