# Setup Nginx server
- name: Setup Web Server
  hosts: localhost

  tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade cache
      become: yes
      apt:
        upgrade: 'yes'

    - name: Install PHP Version 8.1
      become: yes
      apt:
        name:
          - php8.1
          - php8.1-cli
          - php8.1-common
          - php8.1-mysql
          - php8.1-zip
          - php8.1-gd
          - php8.1-mbstring
          - php8.1-curl
          - php8.1-xml
          - php8.1-bcmath
          - php8.1-fpm
        install_recommends: no
        state: present

    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      become: yes
      service:
        name: nginx
        state: started

    - name: Start PHP FPM Sock Service
      become: yes
      service:
        name: php8.1-fpm
        state: started

    - name: Move Laravel Project to Web Server and Change Permissions
      ansible.builtin.shell: |
        cd ~ &&
        sudo mv devops-practice/stackingsandbox /var/www/ &&
        cd /var/www/stackingsandbox/ &&
        sudo chown -R $USER:www-data . &&
        sudo find . -type f -exec chmod 644 {} \; &&
        sudo find . -type d -exec chmod 775 {} \; &&
        sudo chgrp -R www-data storage bootstrap/cache &&
        sudo chmod -R ug+rwx storage bootstrap/cache &&
        cd /var/www/stackingsandbox/ &&
        composer install &&
        cp .env.example .env &&
        php artisan key:generate

  handlers:
    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted

  vars: